### ISSUE TITLE
django-cors-headers not included in requirements.txt

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/nitdgp_website#16]

**Comment by ghoshbishakh** [comment]
Was it left out by mistake? Or am I missing something?

**Comment by devanshgoenka97** [comment]
We shifted to using Pipenv

On 06-Feb-2018 10:48 PM, "Bishakh Ghosh" <notifications@github.com> wrote:

Was it left out by mistake? Or am I missing something?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lugnitdgp/nitdgp_website/issues/16#issuecomment-363496610>,
or mute the thread

**Comment by ghoshbishakh** [comment]
Ok. so lets update the requirements also. so than we can have both the dev env choices (pipenv and virtualenv).
